/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Car_UI_Section;

import Model.CarProduct;
import Model.CarProductHistory;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author dpsmv
 */
public class CreateJPanel extends javax.swing.JPanel {
    Image pic;
    /**
     * Creates new form CreateJPanel
     */
    CarProductHistory history;
    public CreateJPanel(CarProductHistory history) {
        initComponents();
        this.history = history;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLicenseplates = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        lblOnwerTelephonenumbers = new javax.swing.JLabel();
        lblOwnerEmailaddresses = new javax.swing.JLabel();
        lblOwnerDriverlicense = new javax.swing.JLabel();
        lblOwnerSSN = new javax.swing.JLabel();
        txtImage = new javax.swing.JTextField();
        lblOwneraddress = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        lblWarrantyYear = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtEng_Num = new javax.swing.JTextField();
        txtLicense_Plates = new javax.swing.JTextField();
        txtSeat_num = new javax.swing.JTextField();
        txtOwner_Email_Addresses = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        txtOnwer_Telephone_numb = new javax.swing.JTextField();
        lblBrand = new javax.swing.JLabel();
        txtWarranty_Year = new javax.swing.JTextField();
        lblModel = new javax.swing.JLabel();
        txtOwner_Name = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtOwner_Driver_license = new javax.swing.JTextField();
        lblYear = new javax.swing.JLabel();
        txtOwner_SSN = new javax.swing.JTextField();
        lblEngineNo = new javax.swing.JLabel();
        txtOwner_Address = new javax.swing.JTextField();
        lblseatsNumber = new javax.swing.JLabel();
        btnSaveProduct = new javax.swing.JButton();

        lblLicenseplates.setText("Licence plate");

        lblOwnerName.setText("Seats number");

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearKeyPressed(evt);
            }
        });

        lblOnwerTelephonenumbers.setText("Owner Email Address");

        lblOwnerEmailaddresses.setText("Owner Telephone number");

        lblOwnerDriverlicense.setText("Owner Driver licence");

        lblOwnerSSN.setText("OwnerSSN");

        lblOwneraddress.setText("Owner Address");

        btnUpload.setText("Upload Image");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        lblWarrantyYear.setText("Warranty Year");

        lblImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });
        txtBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrandKeyPressed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        txtEng_Num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEng_NumActionPerformed(evt);
            }
        });

        txtLicense_Plates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicense_PlatesActionPerformed(evt);
            }
        });

        txtSeat_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeat_numActionPerformed(evt);
            }
        });

        txtOwner_Email_Addresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwner_Email_AddressesActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Symbol", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Car Product");

        txtOnwer_Telephone_numb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOnwer_Telephone_numbActionPerformed(evt);
            }
        });

        lblBrand.setText("Brand");

        txtWarranty_Year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWarranty_YearActionPerformed(evt);
            }
        });

        lblModel.setText("Model");

        txtOwner_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwner_NameActionPerformed(evt);
            }
        });

        lblColor.setText("Color");

        txtOwner_Driver_license.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwner_Driver_licenseActionPerformed(evt);
            }
        });

        lblYear.setText("Year");

        txtOwner_SSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwner_SSNActionPerformed(evt);
            }
        });

        lblEngineNo.setText("Engine No");

        txtOwner_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwner_AddressActionPerformed(evt);
            }
        });

        lblseatsNumber.setText("Owner Name");

        btnSaveProduct.setFont(new java.awt.Font("Symbol", 1, 14)); // NOI18N
        btnSaveProduct.setText("SAVE");
        btnSaveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblEngineNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOwnerEmailaddresses, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOnwerTelephonenumbers, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblseatsNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOwnerSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblOwnerDriverlicense))
                            .addComponent(lblWarrantyYear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLicenseplates, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblYear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOwner_Driver_license, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwner_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEng_Num, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWarranty_Year, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSeat_num, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtOwner_SSN, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSaveProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOwner_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOnwer_Telephone_numb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOwner_Email_Addresses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpload))
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLicense_Plates, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lblOwneraddress, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtOnwer_Telephone_numb, txtOwner_Email_Addresses, txtOwner_SSN});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSaveProduct, btnUpload});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblModel)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBrand)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicenseplates)
                            .addComponent(txtLicense_Plates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColor)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWarrantyYear)
                            .addComponent(txtWarranty_Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerDriverlicense, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOwner_Driver_license, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtOwner_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblseatsNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerEmailaddresses)
                            .addComponent(txtOnwer_Telephone_numb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerName)
                            .addComponent(txtSeat_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOnwerTelephonenumbers)
                            .addComponent(txtOwner_Email_Addresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpload))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwnerSSN)
                            .addComponent(txtOwner_SSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSaveProduct))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOwneraddress)
                            .addComponent(txtOwner_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEngineNo)
                            .addComponent(txtEng_Num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtOnwer_Telephone_numb, txtOwner_Address, txtOwner_Driver_license, txtOwner_Email_Addresses, txtOwner_Name, txtOwner_SSN});

    }// </editor-fold>//GEN-END:initComponents

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearKeyPressed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser Carimage = new JFileChooser();
        FileNameExtensionFilter CarImageFileType = new FileNameExtensionFilter("*.image","png","jpg","jpeg");
        Carimage.setFileFilter(CarImageFileType);
        Carimage.showOpenDialog(null);
        File file = Carimage.getSelectedFile();
        String filename = file.getAbsolutePath();
        txtImage.setText(filename);
        Image getAttribute = null;
        ImageIcon icon = new ImageIcon(filename);
        Image img = icon.getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH);
        icon.setImage(img);
        lblImage.setIcon(icon);
        pic=img;
    }//GEN-LAST:event_btnUploadActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtBrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandKeyPressed

    }//GEN-LAST:event_txtBrandKeyPressed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtEng_NumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEng_NumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEng_NumActionPerformed

    private void txtLicense_PlatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicense_PlatesActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtLicense_PlatesActionPerformed

    private void txtSeat_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeat_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeat_numActionPerformed

    private void txtOwner_Email_AddressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwner_Email_AddressesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwner_Email_AddressesActionPerformed

    private void txtOnwer_Telephone_numbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOnwer_Telephone_numbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOnwer_Telephone_numbActionPerformed

    private void txtWarranty_YearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarranty_YearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarranty_YearActionPerformed

    private void txtOwner_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwner_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwner_NameActionPerformed

    private void txtOwner_Driver_licenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwner_Driver_licenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwner_Driver_licenseActionPerformed

    private void txtOwner_SSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwner_SSNActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtOwner_SSNActionPerformed

    private void txtOwner_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwner_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwner_AddressActionPerformed

    private void btnSaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProductActionPerformed
        // TODO add your handling code here:
     String Brand = txtBrand.getText();
     String Model =txtModel.getText();
     String Color = txtColor.getText();
     int Year = Integer.parseInt(txtYear.getText());
     int EngineNumber = Integer.parseInt(txtEng_Num.getText());
     int SeatsNumber = Integer.parseInt(txtSeat_num.getText());
     int LicensePlates = Integer.parseInt(txtLicense_Plates.getText());
     String OwnerName = txtOwner_Name.getText();
     int OwnerTelephoneNumbers = Integer.parseInt(txtOnwer_Telephone_numb.getText());
     String OwnerEmailAddress = txtOwner_Email_Addresses.getText();
     String OwnerDriverLicense = txtOwner_Driver_license.getText();
        int OwnerSSN = Integer.parseInt(txtOwner_SSN.getText());
     String Owneraddress = txtOwner_Address.getText();
     int WarrantyYear = Integer.parseInt(txtWarranty_Year.getText());
    
     CarProduct car = history.addNewCarProduct();
     car.setBrand(Brand);
     car.setModel(Model);
     car.setColor(Color);
     car.setYear(Year);
        if(txtYear.getText().trim().length()!=4){
            JOptionPane.showMessageDialog(this, "Invalid Year");
        }
     car.setEngineNumber(EngineNumber);
        if(txtEng_Num.getText().trim().length()!=12){
            JOptionPane.showMessageDialog(this, "Invalid Year");
        }
     car.setSeatsNumber(SeatsNumber);
     car.setLicensePlates(LicensePlates);
     car.setOwnerName(OwnerName);
     car.setOwnerTelephoneNumbers(OwnerTelephoneNumbers);
     car.setOwnerTelephoneNumbers(Integer.parseInt(txtOnwer_Telephone_numb.getText()));
        if(txtOnwer_Telephone_numb.getText().trim().length()!=10){
        JOptionPane.showMessageDialog(this, "Enter Correct Telephone Number");
        }
     car.setOwnerEmailAddress(OwnerEmailAddress);
        if(txtOwner_Email_Addresses.getText().contains("@") && txtOwner_Email_Addresses.getText().contains("."))
        {}
        else
            JOptionPane.showMessageDialog(this, " Invalid Email-Address");
     car.setOwnerDriverLicense(OwnerDriverLicense);
     car.setOwnerSSN(OwnerSSN);
     car.setOwnerSSN(Integer.parseInt(txtOwner_SSN.getText()));
        if(txtOwner_SSN.getText().trim().length()!=9){
            JOptionPane.showMessageDialog(this, "Invalid SSN");
            return;
        }
     car.setOwneraddress(Owneraddress);
     car.setWarrantyYear(WarrantyYear);
     car.setImage(pic);
     if(txtImage.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Image is required");
        }
     JOptionPane.showMessageDialog(this, "Car Profile Created");
     
     txtBrand.setText("");
     txtModel.setText("");
     txtColor.setText("");
     txtYear.setText("");
     txtEng_Num.setText("");
     txtSeat_num.setText("");
     txtLicense_Plates.setText("");
     txtOwner_Name.setText("");
     txtOnwer_Telephone_numb.setText("");
     txtOwner_Email_Addresses.setText("");
     txtOwner_Driver_license.setText("");    
     txtOwner_SSN.setText("");
     txtOwner_Address.setText("");
     txtWarranty_Year.setText("");      
        

    }//GEN-LAST:event_btnSaveProductActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveProduct;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLicenseplates;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOnwerTelephonenumbers;
    private javax.swing.JLabel lblOwnerDriverlicense;
    private javax.swing.JLabel lblOwnerEmailaddresses;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerSSN;
    private javax.swing.JLabel lblOwneraddress;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWarrantyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JLabel lblseatsNumber;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEng_Num;
    private javax.swing.JTextField txtImage;
    private javax.swing.JTextField txtLicense_Plates;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOnwer_Telephone_numb;
    private javax.swing.JTextField txtOwner_Address;
    private javax.swing.JTextField txtOwner_Driver_license;
    private javax.swing.JTextField txtOwner_Email_Addresses;
    private javax.swing.JTextField txtOwner_Name;
    private javax.swing.JTextField txtOwner_SSN;
    private javax.swing.JTextField txtSeat_num;
    private javax.swing.JTextField txtWarranty_Year;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
